import { Component, Inject, ViewEncapsulation, computed, signal } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatRadioModule } from '@angular/material/radio';
import { MatTooltipModule } from '@angular/material/tooltip';
import { CreateQuickShareRequest, QuickShareMode } from '../../../services/quick-shares.api';

export interface CreateQuickShareDialogData {
    selectedFiles: string[];
    selectedFolders: string[];
    excludedFiles: string[];
    excludedFolders: string[];
    defaultName: string;
    appUrl: string;
}

const SLUG_REGEX = /^[a-zA-Z0-9][a-zA-Z0-9-]{1,98}[a-zA-Z0-9]$/;

@Component({
    selector: 'app-create-quick-share-dialog',
    imports: [
        FormsModule,
        MatButtonModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatInputModule,
        MatRadioModule,
        MatTooltipModule
    ],
    templateUrl: './create-quick-share-dialog.component.html',
    styleUrl: './create-quick-share-dialog.component.scss',
    encapsulation: ViewEncapsulation.None
})
export class CreateQuickShareDialogComponent {
    name = signal('');
    mode = signal<QuickShareMode>('browser');
    allowIndividualFileDownload = signal(true);

    customSlug = signal('');
    isCustomSlugValid = computed(() => {
        const slug = this.customSlug().trim();
        if (slug.length === 0) return true;
        return slug.length >= 3 && slug.length <= 100 && SLUG_REGEX.test(slug);
    });

    urlPreview = computed(() => {
        const slug = this.customSlug().trim();
        const placeholder = slug.length > 0 ? slug : '<auto-generated>';
        return `${this.data.appUrl}/share/${placeholder}`;
    });

    expiresAtIso = signal('');
    password = signal('');
    maxDownloads = signal<number | null>(null);

    isSubmitting = signal(false);

    canSubmit = computed(() => {
        if (this.isSubmitting()) return false;
        if (!this.name().trim()) return false;
        if (!this.isCustomSlugValid()) return false;
        const max = this.maxDownloads();
        if (max !== null && max <= 0) return false;
        return true;
    });

    constructor(
        @Inject(MAT_DIALOG_DATA) public data: CreateQuickShareDialogData,
        public dialogRef: MatDialogRef<CreateQuickShareDialogComponent, CreateQuickShareRequest | null>
    ) {
        this.name.set(data.defaultName);
    }

    onModeChange(value: QuickShareMode) {
        this.mode.set(value);
        if (value !== 'browser') {
            this.allowIndividualFileDownload.set(false);
        }
    }

    onCancel() {
        this.dialogRef.close(null);
    }

    // Material's mdc-text-field wraps the input so the native datetime-local picker
    // doesn't open from a regular click. Force it open programmatically.
    openPicker(input: HTMLInputElement) {
        input.showPicker?.();
    }

    onSubmit() {
        if (!this.canSubmit()) return;

        this.isSubmitting.set(true);

        const slug = this.customSlug().trim();
        const password = this.password();
        const max = this.maxDownloads();

        const request: CreateQuickShareRequest = {
            name: this.name().trim(),
            customSlug: slug.length > 0 ? slug : null,
            selectedFiles: this.data.selectedFiles,
            selectedFolders: this.data.selectedFolders,
            excludedFiles: this.data.excludedFiles,
            excludedFolders: this.data.excludedFolders,
            mode: this.mode(),
            allowIndividualFileDownload: this.allowIndividualFileDownload(),
            expiresAt: this.expiresAtIso() ? new Date(this.expiresAtIso()).toISOString() : null,
            password: password.length > 0 ? password : null,
            maxDownloads: max !== null && max > 0 ? max : null
        };

        this.dialogRef.close(request);
    }
}
